### ISSUE TITLE
Azure IoT Edge Tools for VS 2019 v1.9.0: Automatic edit of files each time the project is opened

### ISSUE THREAD

**Issue by martin-weber** [microsoft/vs-azure-iot-edge-docs#32]
**Issue**
Already before version 1.9.0 the .iotedgeproj file was marked as edited without any changes each time the project was opened.
Since version 1.9.0 also the sln file is marked as modified without any changes each time it is opened. 
Since version 1.9.0 the deployment.template.json and deployment.debug.template.json files are edited each time the project is opened by replacing the version numbers of the azureiotedge-agent and the azureiotedge-hub images with DEFAULT_RT_IMAGE.

**Proposal**
It would save a lot of time for developers if this automatic edits could be omitted or at least disabled in the extensions settings.

**Comment by mhshami01** [comment]
Thank you @martin-weber for your feedback. We are currently investigating the issue and hope to have an update soon.

**Comment by TechPreacher** [comment]
I can confirm this behavior. Very weird change if you don't want the extra env. var.

**Comment by mhshami01** [comment]
Hello @martin-weber et al. Today we released a new version of the extension which addresses the issue. Thank you!

**Comment by martin-weber** [comment]
Hello @mhshami01, 
Just updated to Version 2.0.0. I can confirm that the issue with the DEFAULT_RT_IMAGE in the deployment files is gone as well as the one with the solution file. Only the .iotedgeproj still shows up as changed without any changes, but this is no major issue as it was already before version 1.9.0 and does not cause trouble.
Thanks for fixing this so fast.
